const BASE_URL = " https://eventease-q2yh.onrender.com";

export const API_ENDPOINTS = {
  ME: `${BASE_URL}/api/v1/authenticated/me`,
  REGISTER: `${BASE_URL}/api/v1/auth/registerLink`,
  LOGIN: `${BASE_URL}/api/v1/auth/login`,
  CREATE_EVENT: `${BASE_URL}/api/v1/auth/event/createEvent`,
  UPDATE_EVENT_PICTURE: `${BASE_URL}/api/v1/auth/event/updateEventPicture/`,
  UPDATE_EVENT: `${BASE_URL}/api/v1/auth/event/updateEvent/`,
  UPDATE_PROFILE_PICTURE: `${BASE_URL}/api/v1/auth/user/updateProfilePicture/`,
  GET_ALL_EVENTS: `${BASE_URL}/api/v1/auth/event/getAllEvents`,
  GET_EVENT_PICTURE: `${BASE_URL}/api/v1/auth/event/getEventPicture/`,
  GET_ALL_USERS: `${BASE_URL}/api/v1/auth/user/getAllUsers`,
  GET_PROFILE_PICTURE: `${BASE_URL}/api/v1/auth/user/getProfilePicture/`,
  GET_PROFILE_PICTURE_SVG: `${BASE_URL}/api/v1/auth/user/getProfilePicture/svg/`,
  GET_EVENT_BY_ID: `${BASE_URL}/api/v1/auth/event/getEventById/`,
  GET_USER_BY_ID: `${BASE_URL}/api/v1/auth/user/`,
  DELETE_USER: `${BASE_URL}/api/v1/auth/user/deleteUser/`,
  UPDATE_USER: `${BASE_URL}/api/v1/auth/updateUser/`,
  JOIN_EVENT: `${BASE_URL}/api/v1/auth/userevent/joinEvent/`,
  UNJOIN_EVENT: `${BASE_URL}/api/v1/auth/userevent/unjoinEvent/`,
  GET_EVENTS_JOINED_BY_USER: `${BASE_URL}/api/v1/auth/userevent/getAllEventsJoinedByUser/`,
  GET_ALL_USERS_JOINED_TO_EVENT: `${BASE_URL}/api/v1/auth/userevent/getAllUsersJoinedToEvent/`,
  DELETE_EVENT: `${BASE_URL}/api/v1/auth/event/deleteEventById/`,
  GET_ATTENDEES: `${BASE_URL}/api/v1/auth/admin/getAttendanceByAllEvents`,
  GET_TOP_THREE: `${BASE_URL}/api/v1/auth/admin/getTopThree`,
  BLOCK_USER: `${BASE_URL}/api/v1/auth/admin/block/`,
  UNBLOCK_USER: `${BASE_URL}/api/v1/auth/admin/unblock/`,
  GET_ALL_EVENTS_AFTER_ATTENDANCE:`${BASE_URL}/api/v1/auth/admin/getEventsJoinedAttendance/`,
  GET_ALL_USERS_AFTER_ATTENDANCE:`${BASE_URL}/api/v1/auth/admin/getUsersJoinedAfterAttendance/`,
  EVENT_NOW: `${BASE_URL}/api/v1/auth/event/getEventNow`,
  LIKE_EVENT: `${BASE_URL}/api/v1/auth/event/likeEvent/`,
  DISLIKE_EVENT: `${BASE_URL}/api/v1/auth/event/dislikeEvent/`,
  FORGOT_PASSWORD: `${BASE_URL}/api/v1/auth/forgot-password`,
  VERIFY_TOKEN: `${BASE_URL}/api/v1/auth/verifyToken`,
  NEW_PASSWORD: `${BASE_URL}/api/v1/auth/new-password`,
  VERIFY_PASSWORD: `${BASE_URL}/api/v1/auth/verifyPassword/`,
  EVENT_POPULARITY: `${BASE_URL}/api/v1/auth/analytics/getEventPopularity/`,
  JOIN_RATE: `${BASE_URL}/api/v1/auth/analytics/getJoinRate/`,
  EVENT_DISTRIBUTION: `${BASE_URL}/api/v1/auth/analytics/getEventTypeDistribution`,
  SCHEDULING_TRENDS: `${BASE_URL}/api/v1/auth/analytics/getEventSchedulingTrends`,
  AVERAGE_EVENT_DURATION: `${BASE_URL}/api/v1/auth/analytics/getAverageEventDuration`,
  DEPARTMENT_ENGAGEMENT: `${BASE_URL}/api/v1/auth/analytics/getDepartmentEngagement`,
  SET_ADMIN: `${BASE_URL}/api/v1/auth/admin/setAdmin/`,
  SET_STUDENT: `${BASE_URL}/api/v1/auth/admin/setStudent/`,

};