const BASE_URL = "https://king-prawn-app-92pca.ondigitalocean.app";

export const API_ENDPOINTS = {
  ME: `${BASE_URL}/api/v1/authenticated/me`,
  REGISTER: `${BASE_URL}/api/v1/auth/registerLink`,
  LOGIN: `${BASE_URL}/api/v1/auth/login`,
  CREATE_EVENT: `${BASE_URL}/event/createEvent`,
  UPDATE_EVENT_PICTURE: `${BASE_URL}/event/updateEventPicture/`,
  UPDATE_EVENT: `${BASE_URL}/event/updateEvent/`,
  UPDATE_PROFILE_PICTURE: `${BASE_URL}/user/updateProfilePicture/`,
  GET_ALL_USERS: `${BASE_URL}/user/getAllUsers`,
  GET_PROFILE_PICTURE: `${BASE_URL}/user/getProfilePicture/`,
  GET_PROFILE_PICTURE_SVG: `${BASE_URL}/user/getProfilePicture/svg/`,
  GET_EVENT_BY_ID: `${BASE_URL}/event/getEventById/`,
  GET_USER_BY_ID: `${BASE_URL}/user/`,
  DELETE_USER_BY_ADMIN: `${BASE_URL}/admin/deleteUserByAdmin/`,
  DELETE_USER: `${BASE_URL}/user/deleteUser/`,
  UPDATE_USER: `${BASE_URL}/user/updateUser/`,
  JOIN_EVENT: `${BASE_URL}/userevent/joinEvent/`,
  UNJOIN_EVENT: `${BASE_URL}/userevent/unjoinEvent/`,
  GET_EVENTS_JOINED_BY_USER: `${BASE_URL}/userevent/getAllEventsJoinedByUser/`,
  GET_ALL_USERS_JOINED_TO_EVENT: `${BASE_URL}/userevent/getAllUsersJoinedToEvent/`,
  DELETE_EVENT: `${BASE_URL}/event/deleteEventById/`,
  GET_ATTENDEES: `${BASE_URL}/admin/getAttendanceByAllEvents`,
  GET_TOP_THREE: `${BASE_URL}/admin/getTopThree`,
  BLOCK_USER: `${BASE_URL}/admin/block/`,
  UNBLOCK_USER: `${BASE_URL}/admin/unblock/`,
  GET_ALL_EVENTS_AFTER_ATTENDANCE: `${BASE_URL}/admin/getEventsJoinedAttendance/`,
  GET_ALL_USERS_AFTER_ATTENDANCE: `${BASE_URL}/admin/getUsersJoinedAfterAttendance/`,
  GET_ATTENDANCE_AND_TIMEOUT: `${BASE_URL}/admin/getAllAttendanceAndTimeout/`,
  EVENT_NOW: `${BASE_URL}/event/getEventNow`,
  LIKE_EVENT: `${BASE_URL}/event/likeEvent/`,
  DISLIKE_EVENT: `${BASE_URL}/event/dislikeEvent/`,
  
  FORGOT_PASSWORD: `${BASE_URL}/api/v1/auth/forgot-password`,
  VERIFY_TOKEN: `${BASE_URL}/api/v1/auth/verifyToken`,
  NEW_PASSWORD: `${BASE_URL}/api/v1/auth/new-password`,
  VERIFY_PASSWORD: `${BASE_URL}/api/v1/auth/verifyPassword/`,
  HELLO: `${BASE_URL}/api/v1/auth/hello`,
  CONFIRM: `${BASE_URL}/api/v1/auth/confirm`,
  REGISTER_LINK: `${BASE_URL}/api/v1/auth/registerLink`,
  TEST: `${BASE_URL}/api/v1/auth/test`,
  CALL_CRON: `${BASE_URL}/api/v1/auth/callCron`,
  
  GET_ALL_EVENTS: `${BASE_URL}/api/v1/auth/event/getAllEvents`,
  GET_EVENT_PICTURE: `${BASE_URL}/api/v1/auth/event/getEventPicture/`,
  EVENT_POPULARITY: `${BASE_URL}/analytics/getEventPopularity/`,
  JOIN_RATE: `${BASE_URL}/analytics/getJoinRate/`,
  EVENT_DISTRIBUTION: `${BASE_URL}/analytics/getEventTypeDistribution`,
  SCHEDULING_TRENDS: `${BASE_URL}/analytics/getEventSchedulingTrends`,
  AVERAGE_EVENT_DURATION: `${BASE_URL}/analytics/getAverageEventDuration`,
  DEPARTMENT_ENGAGEMENT: `${BASE_URL}/analytics/getDepartmentEngagement`,
  SET_ADMIN: `${BASE_URL}/admin/setAdmin/`,
  SET_STUDENT: `${BASE_URL}/admin/setStudent/`,

};
